server:
  base_url: https://api.haiemdavang.id.vn
  fe:
    base_url: https://shop.haiemdavang.id.vn
    oauth2:
      redirect-uri: ${server.fe.base_url}/login
  servlet:
    session:
      cookie:
        domain: haiemdavang.id.vn

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&rewriteBatchedStatements=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
        url: ${REDIS_URL}
  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
  elasticsearch:
    uris: http://${ES_HOST}:${ES_PORT}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GG_CLIENT_ID}
            client-secret: ${GG_CLIENT_SECRET}
            redirect-uri: ${server.base_url}${GG_URL_REDIRECT:/oauth2/callback/google}
            scope:
              - email
              - profile

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_KEY}
  api-secret: ${CLOUDINARY_SECRET}
payment:
  vnPay:
    url: ${VNP_URL}
    returnUrl: ${server.base_url}/api/public/vnpay/payment-callback
    tmnCode: ${VNP_TMCODE}
    secretKey: ${VNP_SECRET_KEY}
    version: ${VNP_VER}
    command: ${VNP_COMD}
    orderType: ${VNP_TYPE}
    timeExpire: ${VNP_MAX_TIME}
gemini:
  api-key: ${GEMINI_API_KEY}
jwt:
  token:
    secret_Key: ${JWT_SECRET_KEY}
ghn:
  token: ${GHN_TOKEN}
  shop_id: ${GHN_SHOPID}