spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_anrealShop_test_2}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&rewriteBatchedStatements=true
    username: ${DB_USERNAME:haiemdavang}
    password: ${DB_PASSWORD:haiemdavang}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  data:
    redis:
      url: ${REDIS_URL}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:""}
    password: ${EMAIL_PASSWORD:""}
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.debug: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT:9092}
    consumer:
      properties:
        max.poll.interval.ms: 900000
        session.timeout.ms: 60000
        heartbeat.interval.ms: 15000

  elasticsearch:
    uris: http://${ES_HOST:localhost}:${ES_PORT:9200}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GG_CLIENT_ID:hello}
            client-secret: ${GG_CLIENT_SECRET:hello}
            redirect-uri: ${server.base_url}${GG_URL_REDIRECT:/oauth2/callback/google}
            scope:
              - email
              - profile

logging:
  level:
    org:
      springframework:
        cache: DEBUG
        data.redis.serializer: debug
        web.socket: DEBUG
        messaging: debug
      elasticsearch:
        client: TRACE
      hibernate.jdbc.BatchingBatch: TRACE


server:
  base_url: http://localhost:4141
  fe:
    base_url: http://localhost:5173
  servlet:
    session:
      cookie:
        domain: localhost
  port: 4141



cloudinary:
  cloud-name: ${CLOUDINARY_NAME:xem_cc}
  api-key: ${CLOUDINARY_KEY:xem_cc}
  api-secret: ${CLOUDINARY_SECRET:xem_cc}

payment:
  vnPay:
    url: ${VNP_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    returnUrl: https://api.haiemdavang.id.vn/api/public/vnpay/payment-callback
    tmnCode: ${VNP_TMCODE:Your-TMN-Code}
    secretKey: ${VNP_SECRET_KEY:Your-Secret-Key}
    version: ${VNP_VER:2.1.0}
    command: ${VNP_COMD:pay}
    orderType: ${VNP_TYPE:billpayment}
    timeExpire: ${VNP_MAX_TIME:15}


gemini:
  api-key: ${GEMINI_API_KEY:your_api_key}

jwt:
  token:
    secret_Key: ${JWT_SECRET_KEY:""}
    expiration: 86400000
    expiration_refresh: 172800000
    cookie_access_name: "ACCESS_TOKEN"
    cookie_refresh_name: "REFRESH_TOKEN"

ghn:
  token: ${GHN_TOKEN:your_ghn_token}
  shop_id: ${GHN_SHOPID:your_ghn_shop_id}